-- 테이블 주석
ALTER TABLE product COMMENT '예금 상품 정보';
ALTER TABLE account COMMENT '계좌 정보';
ALTER TABLE `transaction` COMMENT '거래 내역';

-- product 컬럼 주석
ALTER TABLE product MODIFY COLUMN code VARCHAR(20) NOT NULL COMMENT '상품 코드';
ALTER TABLE product MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '상품명';
ALTER TABLE product MODIFY COLUMN description TEXT COMMENT '상품 설명';
ALTER TABLE product MODIFY COLUMN interest_rate DECIMAL(5,4) COMMENT '기본 금리 (예: 3.5% = 0.0350)';

-- account 컬럼 주석
ALTER TABLE account MODIFY COLUMN account_number VARCHAR(20) NOT NULL COMMENT '계좌번호';
ALTER TABLE account MODIFY COLUMN product_code VARCHAR(20) NOT NULL COMMENT '상품 코드 (FK)';
ALTER TABLE account MODIFY COLUMN balance DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '잔액';
ALTER TABLE account MODIFY COLUMN status ENUM('ACTIVE','CLOSED') NOT NULL DEFAULT 'ACTIVE' COMMENT '계좌 상태';
ALTER TABLE account MODIFY COLUMN opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '개설일시';
ALTER TABLE account MODIFY COLUMN closed_at TIMESTAMP NULL COMMENT '해지일시';

-- transaction 컬럼 주석
ALTER TABLE `transaction` MODIFY COLUMN transaction_number VARCHAR(30) NOT NULL COMMENT '거래번호';
ALTER TABLE `transaction` MODIFY COLUMN account_number VARCHAR(20) NOT NULL COMMENT '계좌번호 (FK)';
ALTER TABLE `transaction` MODIFY COLUMN type ENUM('DEPOSIT','WITHDRAWAL','TRANSFER_IN','TRANSFER_OUT') NOT NULL COMMENT '거래 유형';
ALTER TABLE `transaction` MODIFY COLUMN amount DECIMAL(18,2) NOT NULL COMMENT '거래 금액';
ALTER TABLE `transaction` MODIFY COLUMN balance_after DECIMAL(18,2) NOT NULL COMMENT '거래 후 잔액';
ALTER TABLE `transaction` MODIFY COLUMN transaction_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '거래일시';
